AWSTemplateFormatVersion: "2010-09-09"
Description: This CloudFormation template deploys Slack webhooks for PHD usage to the AWS Secrets Manager - 1.0.0

#-----------------------------------------------------------
# Parameters
#-----------------------------------------------------------

Parameters:
  OrganizationId:
    Type: String
    Description: Organization ID used to limit access to Org accounts
    Default: "o-1234567890"
  cloudSlackhook:
    Type: String
    NoEcho: true
    Description: Slack webhook for Cloud team accounts and other undefined accounts
  legacySlackhook:
    Type: String
    NoEcho: true
    Description: Slack webhook for legacy accounts
  windowsSlackhook:
    Type: String
    NoEcho: true
    Description: Slack webhook for Windows team accounts
  TagKey:
    Type: String
    Description: Tag key for the secret
    Default: Application
  TagValue:
    Type: String
    Description: Tag value for the secret
    Default: PHD

#-----------------------------------------------------------
# Resources
#-----------------------------------------------------------

Resources:
  KmsKey:
    Type: "AWS::KMS::Key"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F76 # Potentially need to change id value
            reason: A '*' principal warning, doesn't take into account that access is limited by Org ID
    Properties:
      Description: KMS key used for phd secrets encryption.
      EnableKeyRotation: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Allow direct access to key metadata to the account
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Sid: Allow KMS access to the Organization
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Sub ${OrganizationId}

  PHDSlackCloud:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Slack webhook for Cloud team accounts and other undefined accounts"
      Name: "phd/slackhook/cloud"
      KmsKeyId: !GetAtt "KmsKey.KeyId"
      SecretString: !Sub '{"phdslackhook": "Iamcloudy.com"}'
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  PHDSlackCloudPolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref PHDSlackCloud
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
          - Resource: "*"
            Action: "secretsmanager:GetSecretValue"
            Effect: Allow
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Sub ${OrganizationId}

  PHDSlackLegacy:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Slack webhook for legacy accounts"
      Name: "phd/slackhook/legacy"
      KmsKeyId: !GetAtt "KmsKey.KeyId"
      SecretString: !Sub '{"phdslackhook": "Iamold.com"}'
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  PHDSlackLegacyPolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref PHDSlackLegacy
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
          - Resource: "*"
            Action: "secretsmanager:GetSecretValue"
            Effect: Allow
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Sub ${OrganizationId}

  PHDSlackWindows:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Slack webhook for Windows team accounts"
      Name: "phd/slackhook/windows"
      KmsKeyId: !GetAtt "KmsKey.KeyId"
      SecretString: !Sub '{"phdslackhook": "Imwindows.com"}'
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue

  PHDSlackWindowsPolicy:
    Type: "AWS::SecretsManager::ResourcePolicy"
    Properties:
      SecretId: !Ref PHDSlackWindows
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
          - Resource: "*"
            Action: "secretsmanager:GetSecretValue"
            Effect: Allow
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Sub ${OrganizationId}

Outputs:
  PHDSlackCloud:
    Description: Cloud team slack secret arn
    Value: !Ref PHDSlackCloud
  PHDSlackLegacy:
    Description: Legacy team slack secret arn
    Value: !Ref PHDSlackLegacy
  PHDSlackWindows:
    Description: Windows team slack secret arn
    Value: !Ref PHDSlackWindows
